apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chishiya-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
  - host: chishiya.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chishiya-service
            port:
              number: 80
